source = ~/.config/hypr/env.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/animation.conf 

#  laptop only
monitor = eDP-1, highres, 0x0, 1
monitor = eDP-1, disable

# other monitor
monitor = DP-3, 2560x1440@144, 0x0, 1
monitor = DP-4, 1920x1080@144, auto-left, 1, transform, 3

input {
  kb_layout = fr
  repeat_rate = 40
  repeat_delay = 375
  follow_mouse = 2
  sensitivity = 0
  float_switch_override_focus = 0
  touchpad {
    natural_scroll = true
  }
}

gestures {
  workspace_swipe = true
}

general {
    gaps_in = 10
    gaps_out = 15
    border_size = 0
    # col.active_border = rgba(FFFFFFaa)
    # col.inactive_border = rgba(595959aa)
    col.active_border = rgb(b4befe) rgb(f5c2e7) 45deg
    # col.inactive_border = rgba(00000000)
    layout = dwindle
    resize_on_border = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = true
  vrr = 0
  animate_manual_resizes = false
  mouse_move_focuses_monitor = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
}

decoration {
    rounding = 15

    active_opacity = 1.0
    inactive_opacity = 1.0

  # layerrule = blur,waybar

    blur {
      enabled = true
      special = true
      popups = true
      ignore_opacity = false
      xray = false
      size = 5
      #special = true
      passes = 3
      contrast = 1
      brightness = 0.75
      vibrancy = 0
      noise = 0
    }
}

dwindle {
    preserve_split = yes
}
