source = ~/.config/hypr/modules/env.conf
source = ~/.config/hypr/modules/startup.conf
source = ~/.config/hypr/modules/windowrule.conf
source = ~/.config/hypr/modules/keybinds.conf
source = ~/.config/hypr/modules/animation.conf

#  Laptop Screen Only
monitor = eDP-1, preffered, 0x0, 1
# monitor = eDP-1, disable

# External monitor
# moniltor = DP-2, 2560x1440@120, 0x0, 1
# monitor = DP-3, 1920x1080@144, auto-left, 1, transform, 3

# Example for other monitor
# Do the hyprctl monitors command to see the name and the resolution of the screen
# monitor = Screen Name, Resolution, Position, Scale

input {
  kb_layout = fr
  repeat_rate = 40
  repeat_delay = 375
  follow_mouse = 0
  sensitivity = 0
  float_switch_override_focus = 0
  touchpad {
    natural_scroll = true
  }
}

general {
    gaps_in = 9
    gaps_out = 13
    border_size = 1
    col.active_border = rgb(b4befe) rgb(f5c2e7) 45deg
    layout = dwindle
    resize_on_border = true
}

misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  mouse_move_enables_dpms = true
  vfr = true
  vrr = 0
  animate_manual_resizes = false
  mouse_move_focuses_monitor = true
  enable_swallow = true
  swallow_regex = ^(kitty)$
}

gesture {
  gesture = 3, horizontal, workspace,
}

decoration {
    rounding = 15

    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
      enabled = true
      special = true
      popups = true
      ignore_opacity = false
      xray = false
      size = 7
      passes = 4
      contrast = 1
      brightness = 0.75
      vibrancy = 0
      noise = 0
    }
}

dwindle {
    preserve_split = yes
}

plugin {
   hyprexpo {
    columns = 3
    gap_size = 5
    workspace_method = first 1 # [center/first] [workspace] e.g first 1 or center m+1
   }

   hyprfocus {
     mode = slide
   }
}
